openapi: 3.0.3
info:
  version: '1.0'
  title: User data proxy API
servers:
  - url: http://localhost:8080/
paths:
  /users/{login}:
    get:
      summary: Fetches user data from GitHub
      tags:
        - UserData
      operationId: fetchUserData
      parameters:
        - in: path
          name: login
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Fetch successful.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDataResponse'
        '404':
          description: Not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '503':
          description: Service unavailable.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    UserDataResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        login:
          type: string
        name:
          type: string
        type:
          type: string
        avatarUrl:
          type: string
        createdAt:
          type: string
          format: date-time
        calculations:
          type: number
          format: double
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
          format: int32
tags:
  - name: UserData